package resolver_user

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	graph_model "metabox-school-bac-giang-request-service/src/graph/generated/model"
	generated_user "metabox-school-bac-giang-request-service/src/graph/generated/user"
	"metabox-school-bac-giang-request-service/src/network"
	service_request "metabox-school-bac-giang-request-service/src/service/request"

	"github.com/99designs/gqlgen/graphql"
)

// RequestAdd is the resolver for the requestAdd field.
func (r *mutationResolver) RequestAdd(ctx context.Context, data graph_model.RequestAdd) (*graph_model.Request, error) {
	input := &service_request.RequestAddCommand{
		Username: data.Username,
		Note:     data.Note,
		Phone:    data.Phone,
	}

	result, err := service_request.RequestAdd(ctx, input)
	if err != nil {
		return &graph_model.Request{}, err
	}

	return result.ConvertToModelGraph(), nil
}

// RequestUpdate is the resolver for the requestUpdate field.
func (r *mutationResolver) RequestUpdate(ctx context.Context, data graph_model.RequestUpdate) (*graph_model.Request, error) {
	input := &service_request.RequestUpdateCommand{
		RequestID: data.RequestID,
		Note:      data.Note,
		Phone:     data.Phone,
	}

	result, err := service_request.RequestUpdate(ctx, input)
	if err != nil {
		return &graph_model.Request{}, err
	}

	return result.ConvertToModelGraph(), nil
}

// RequestDelete is the resolver for the requestDelete field.
func (r *mutationResolver) RequestDelete(ctx context.Context, data graph_model.RequestDelete) (*graph_model.Request, error) {
	input := &service_request.RequestDeleteCommand{
		RequestID: data.RequestID,
	}

	result, err := service_request.RequestDelete(ctx, input)
	if err != nil {
		return &graph_model.Request{}, err
	}

	return result.ConvertToModelGraph(), nil
}

// RequestPagination is the resolver for the requestPagination field.
func (r *queryResolver) RequestPagination(ctx context.Context, page int, limit int, orderBy *string, search map[string]interface{}) (*graph_model.RequestPagination, error) {
	input := &service_request.RequestPaginationCommand{
		Page:  page,
		Limit: limit,
	}

	if orderBy != nil {
		input.OrderBy = *orderBy
	}

	if search != nil {
		input.Search = search
	}

	total, result, err := service_request.RequestPagination(ctx, input)
	if err != nil {
		if graphql.GetErrors(ctx) == nil {
			return nil, err
		}
		return nil, nil
	}

	requests := make([]graph_model.Request, 0)
	for i := 0; i < len(result); i++ {
		requests = append(requests, *result[i].ConvertToModelGraph())
	}

	return &graph_model.RequestPagination{
		Rows: requests,
		Paging: graph_model.Pagination{
			CurrentPage: page,
			Limit:       limit,
			TotalPage:   CalculateTotalPage(total, limit),
			Total:       total,
		},
	}, nil
}

// RequestMe is the resolver for the requestMe field.
func (r *queryResolver) RequestMe(ctx context.Context) (*graph_model.RequestPagination, error) {
	input := &service_request.RequestMeCommand{
		Username: network.Username(ctx),
	}

	result, err := service_request.RequestMe(ctx, input)
	if err != nil {
		return &graph_model.RequestPagination{}, err
	}

	requests := make([]graph_model.Request, 0)
	for i := 0; i < len(result); i++ {
		requests = append(requests, *result[i].ConvertToModelGraph())
	}

	return &graph_model.RequestPagination{
		Rows: requests,
	}, nil
}

// Mutation returns generated_user.MutationResolver implementation.
func (r *Resolver) Mutation() generated_user.MutationResolver { return &mutationResolver{r} }

// Query returns generated_user.QueryResolver implementation.
func (r *Resolver) Query() generated_user.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
